### ISSUE TITLE
Unable to build documentation after upgrading to 0.3.1

### ISSUE THREAD

**Issue by usrme** [mkdocstrings/autorefs#14]
I've pinned the version of `mkdocstrings` to 0.16.2, but that "only" narrows the versions of `mkdocs-autorefs` to **<0.4,>=0.1**, which would probably normally be fine. However, I recently found out that I am no longer able to build my documentation. Here's a quick example of it working with 0.3.0:

```console
$ pip show mkdocs-autorefs
Name: mkdocs-autorefs
Version: 0.3.0
Summary: Automatically link across pages in MkDocs.
Home-page: https://github.com/mkdocstrings/autorefs
Author: Oleh Prypin
Author-email: oleh@pryp.in
License: ISC
Location: /usr/local/lib/python3.9/site-packages
Requires: Markdown, mkdocs
Required-by: mkdocstrings
$ mkdocs build --strict
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /some/path/public
INFO     -  Documentation built in 1.61 seconds
```

And here's what I get with 0.3.1:

```console
$ pip install mkdocs-autorefs=="0.3.1"
Collecting mkdocs-autorefs==0.3.1
  Downloading mkdocs_autorefs-0.3.1-py3-none-any.whl (8.9 kB)
...
Installing collected packages: mkdocs-autorefs
  Attempting uninstall: mkdocs-autorefs
    Found existing installation: mkdocs-autorefs 0.3.0
    Uninstalling mkdocs-autorefs-0.3.0:
      Successfully uninstalled mkdocs-autorefs-0.3.0
Successfully installed mkdocs-autorefs-0.3.1
$ pip show mkdocs-autorefs
Name: mkdocs-autorefs
Version: 0.3.1
Summary: Automatically link across pages in MkDocs.
Home-page: https://github.com/mkdocstrings/autorefs
Author: Oleh Prypin
Author-email: oleh@pryp.in
License: ISC
Location: /usr/local/lib/python3.9/site-packages
Requires: Markdown, mkdocs
Required-by: mkdocstrings
$ mkdocs build --strict
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /some/path/public
ERROR    -  Error building page 'reference/core.md': 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mkdocs_autorefs/plugin.py", line 88, in get_item_url
    url = self._url_map[identifier]
KeyError: 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/__main__.py", line 187, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 314, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/usr/local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 220, in _build_page
    output = config['plugins'].run_event(
  File "/usr/local/lib/python3.9/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mkdocs_autorefs/plugin.py", line 197, in on_post_page
    fixed_output, unmapped = fix_refs(output, url_mapper)
  File "/usr/local/lib/python3.9/site-packages/mkdocs_autorefs/references.py", line 186, in fix_refs
    html = AUTO_REF_RE.sub(fix_ref(url_mapper, unmapped), html)
  File "/usr/local/lib/python3.9/site-packages/mkdocs_autorefs/references.py", line 156, in inner
    url = url_mapper(unescape(identifier))
  File "/usr/local/lib/python3.9/site-packages/mkdocs_autorefs/plugin.py", line 95, in get_item_url
    for new_identifier in new_identifiers:
TypeError: 'NoneType' object is not iterable
```

The `reference/core.md` file is as follows:

```text
::: <package name>.core
```

Thanks for everything and let me know if I can provide anything else to help solve this.

**Comment by pawamoy** [comment]
Yes I should have released autorefs as 0.4.0 instead of 0.3.1, that was an oversight. While I investigate and resolve the issue, you can forbid version 0.3.1 in your dependencies.

**Comment by usrme** [comment]
Unfortunately I'm working on a private code base for work, so I am unable to share publicly, but if you have any hypotheses that you think might be the cause then we can discuss privately and I can help you that way.

**Comment by pawamoy** [comment]
OK, I thought you were saying that you had this issue with *both* mkdocstrings 0.17.0 *and* mkdocs-autorefs 0.3.1.
But now that I re-read the issue, I think you just have to upgrade to mkdocstrings 0.17.0 (and mkdocs-autorefs). That was the second mistake I made, not forcing at least mkdocs-autorefs 0.3.1 in mkdocstrings 0.17.0(this will be fixed in next version).

**Comment by usrme** [comment]
I can confirm that using version 0.17.0 of `mkdocstrings` solves this issue. Thank you for the quick response!
